name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: go get
      - run: GOOS=windows GOARCH=amd64 go build -o dist/ntlm-response.win-amd64.exe *.go
      - run: GOOS=linux GOARCH=amd64 go build -o dist/ntlm-response.linux-amd64 *.go
      - run: GOOS=darwin GOARCH=amd64 go build -o dist/ntlm-response.darwin-amd64 *.go
      - run: GOOS=linux GOARCH=arm64 go build -o dist/ntlm-response.linux-arm64 *.go
      - run: GOOS=linux GOARCH=arm GOARM=6 go build -o dist/ntlm-response.linux-arm6 *.go
      - run: GOOS=linux GOARCH=arm GOARM=7 go build -o dist/ntlm-response.linux-arm7 *.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*
      
